name: Validate genesis transactions
#  Tests / Code Coverage workflow runs unit tests and uploads a code coverage report
#  This workflow is run on pushes to master & every Pull Requests where a .go, .mod, .sum have been changed
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test-morpheus-apollo-1:
    name: Test morpheus-apollo-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Setup scripts
        run: |
          cd .scripts
          go mod tidy

      - name: Validate genesis transactions
        run: go run .scripts/verify-gentx.go "$GITHUB_WORKSPACE/morpheus-apollo-1"